// priority: 0

console.info('Starting recipe modification scripts...')

onEvent('item.registry', event => {
	// Register new items here
	// event.create('example_item').displayName('Example Item')
event.create('mark_miner').displayName('I.矿工徽章').glow(true)
event.create('mark_farmer').displayName('I.农夫徽章').glow(true)
event.create('mark_warrior').displayName('I.战士徽章').glow(true)
event.create('mark_archer').displayName('I.弓箭手徽章').glow(true)
event.create('mark_wizard').displayName('I.巫师徽章').glow(true)
event.create('mark_pirate').displayName('I.海匪徽章').glow(true)
event.create('mark_thief').displayName('I.盗贼徽章').glow(true)
event.create('mark_huntsman').displayName('I.猎人徽章').glow(true)
event.create('mark_healer').displayName('I.牧师徽章').glow(true)
event.create('mark_pitfighter').displayName('I.角斗士徽章').glow(true)
event.create('mark_tamer').displayName('I.驯兽师徽章').glow(true)

event.create('mark_spelunker').displayName('II.洞穴探险者徽章').glow(true)
event.create('mark_rancher').displayName('II.农场主徽章').glow(true)
event.create('mark_mercenary').displayName('II.佣兵徽章').glow(true) 
event.create('mark_arbalester').displayName('II.弓弩徽章').glow(true) 
event.create('mark_alchemist').displayName('II.炼金师徽章').glow(true) 
event.create('mark_corsair').displayName('II.海盗徽章').glow(true)
event.create('mark_bandit').displayName('II.强盗徽章').glow(true)
event.create('mark_tracker').displayName('II.追踪者徽章').glow(true) 
event.create('mark_spiritualist').displayName('II.灵魂巫师徽章').glow(true) 
event.create('mark_fighter').displayName('II.斗士徽章').glow(true)
event.create('mark_summoner').displayName('II.召唤师徽章').glow(true)

event.create('mark_cavemaster').displayName('III.洞穴征服者徽章').glow(true)
event.create('mark_agrarian').displayName('III.农业大师徽章').glow(true)
event.create('mark_champion').displayName('III.冠军徽章').glow(true)
event.create('mark_artillerist').displayName('III.炮手徽章').glow(true)
event.create('mark_thaumaturge').displayName('III.奇术师徽章').glow(true)
event.create('mark_captain').displayName('III.船长徽章').glow(true)
event.create('mark_rogue').displayName('III.恶棍徽章').glow(true)
event.create('mark_pursuer').displayName('III.捕猎者徽章').glow(true)
event.create('mark_shaman').displayName('III.萨满徽章').glow(true)
event.create('mark_underdog').displayName('III.弑弱者徽章').glow(true)
event.create('mark_beastmaster').displayName('III.野兽大师徽章').glow(true)

event.create('arrow_down').displayName('绿色向下箭头图标')
event.create('arrow_down_yellow').displayName('黄色向下箭头图标')
event.create('arrow_up').displayName('向上箭头图标')
event.create('arrow_left').displayName('向左箭头图标')

event.create('copper_coin').displayName('铜币').tooltip('通过任务获得')
event.create('iron_coin').displayName('铁币').tooltip('通过任务获得')
event.create('gold_coin').displayName('金币').tooltip('通过任务获得')
event.create('diamond_coin').displayName('钻石币').tooltip('通过任务获得')
event.create('netherite_coin').displayName('下界合金币').tooltip('通过任务获得')
event.create('monster_coin').displayName('怪物币')
event.create('nether_coin').displayName('下界币').tooltip('通过完成下界章节任务获得')
//event.create('end_coin').displayName('End Coin').tooltip('Acquired from defeating Champions in the End')

event.create('diamond_nugget').displayName('钻石粒')
event.create('emerald_nugget').displayName('绿宝石粒')
event.create('emerald_ingot').displayName('绿宝石锭')
  
event.create('coin_01').displayName('硬币').tooltip('你可以售卖有价值的材料来获得硬币')
event.create('coin_02').displayName('几枚硬币').tooltip('你可以售卖有价值的材料来获得硬币')
event.create('coin_03').displayName('一组硬币').tooltip('你可以售卖有价值的材料来获得硬币')
event.create('coin_04').displayName('一堆硬币').tooltip('你可以售卖有价值的材料来获得硬币')
event.create('coin_05').displayName('十多个硬币').tooltip('你可以售卖有价值的材料来获得硬币')
event.create('coin_06').displayName('大量金币').tooltip('你可以售卖有价值的材料来获得硬币')

event.create('coin_q_1').displayName('任务硬币').tooltip('你可以做任务获得这些硬币')
event.create('coin_q_2').displayName('任务硬币').tooltip('你可以做任务获得这些硬币')


event.create('star').displayName('星星').glow(true)
event.create('medal').displayName('奖章').glow(true)
event.create('heart').displayName('一颗心')
event.create('heart-half').displayName('半颗心')
event.create('caution').displayName('警告')
event.create('chest').displayName('箱子')
event.create('chest2').displayName('箱子 2')
event.create('fire').displayName('火')
event.create('forbid').displayName('禁止')
event.create('help').displayName('帮助')
event.create('key').displayName('钥匙')
event.create('key_01d').displayName('旧钥匙')
event.create('lightning').displayName('闪电')
event.create('lock').displayName('锁')
event.create('lock-2').displayName('未上锁的锁')
event.create('mark').displayName('标记')
event.create('skull').displayName('骷髅')
event.create('skull2').displayName('骷髅')
event.create('skull3').displayName('骷髅')
event.create('ace').displayName('黑桃A')
event.create('armour').displayName('装备')
event.create('bleed').displayName('流血')
event.create('book2').displayName('书')
event.create('book3').displayName('书')
event.create('book4').displayName('书')
event.create('book_02f').displayName('书')
event.create('book_04g').displayName('书')
event.create('campfire').displayName('假篝火')
event.create('dice').displayName('骰子')
event.create('letter').displayName('信')
event.create('magnifier').displayName('放大镜')
event.create('manuscript').displayName('手稿')
event.create('map').displayName('宝藏地图')
event.create('mine').displayName('采掘')
event.create('ruby').displayName('假红宝石')
event.create('scroll').displayName('卷轴')
event.create('scroll2').displayName('卷轴')
event.create('scroll_01c').displayName('卷轴')
event.create('magicscroll').displayName('魔法卷轴')
event.create('slash').displayName('挥砍')
event.create('spellbook_01d').displayName('魔法书')
event.create('spyglass').displayName('望远镜')
event.create('levelup').displayName('升级')
event.create('shield').displayName('盾牌')
event.create('ring').displayName('指环')
event.create('amulet').displayName('护身符')
event.create('rucksack').displayName('背包')
event.create('bomb').displayName('炸弹')
event.create('dodge').displayName('闪避')
event.create('scaling').displayName('缩放')

event.create('fox').displayName('ShadowFoxy赞助者图标')
event.create('kruscle').displayName('Kruscle赞助者图标')
event.create('plua').displayName('ShadowFoxy Patreon赞助者图标')
event.create('crankonator').displayName('Kruscle Patreon赞助者图标')
event.create('lexileexx').displayName('LexiLeeXx Patreon赞助者图标')
})
onEvent('block.registry', event => {
	// Register new blocks here
	// event.create('example_block').material('wood').hardness(1.0).displayName('Example Block')
	
	event.create('glass_stairs')
	.type('stairs')
  	   .material('glass')
       .hardness(0.3)
       .resistance(0.3)
       .opaque(false)
	 .renderType('cutout')
       .displayName('玻璃楼梯')
	 .textureAll('minecraft:blocks/glass')
	.transparent(true)
	.defaultTranslucent()
	.waterlogged()

  event.create('glass_slab')
	.type('slab')
  	   .material('glass')
       .hardness(0.3)
       .resistance(0.3)
       .opaque(false)
	 .renderType('cutout')
       .displayName('玻璃台阶')
	 .textureAll('minecraft:blocks/glass')
	.transparent(true)
	.defaultTranslucent()
	.waterlogged()

	event.create('ccc1').displayName('压缩铜币').material('metal').hardness(1.0).harvestTool('pickaxe', 1)
	event.create('ccc2').displayName('双重压缩铜币').material('metal').hardness(1.5).harvestTool('pickaxe', 1)
	event.create('ccc3').displayName('三重压缩铜币').material('metal').hardness(2.0).harvestTool('pickaxe', 1)
	event.create('ccc4').displayName('四重压缩铜币').material('metal').hardness(2.5).harvestTool('pickaxe', 1)
	event.create('ccc5').displayName('五重压缩铜币').material('metal').hardness(3.0).harvestTool('pickaxe', 1)
	event.create('ccc6').displayName('六重压缩铜币').material('metal').hardness(3.5).harvestTool('pickaxe', 1)
	event.create('ccc7').displayName('七重压缩铜币').material('metal').hardness(4.0).harvestTool('pickaxe', 1)
	event.create('ccc8').displayName('八重压缩铜币').material('metal').hardness(4.5).harvestTool('pickaxe', 1)
})
